WIP: add QuizBot
qbreader/website pull request #262
Opened 2024-02-20 04:44 UTC by JeliHacker

A bot solution for issue #10. It's not true artificial intelligence, but this lets users play against the computer. 
Like @geoffrey-wu said, 

> Or, the AI can just buzz within a certain range (range would change based on difficulty)

This PR still needs work, the two main things I want to add are better bot difficulty, and making it so the bot buzzes in more like a human (types out the answer instead of just completely interrupting the question). 

I made this a feature for multiplayer rooms instead of single player. I just find myself using a multiplayer room by myself instead of single player mode. Could be personal preference though

2024-05-16 20:25 UTC, VillainsRule requested changes
Few nitpicks from a security standpoint. I love this PR idea, keep it up!

2024-05-16 20:25 UTC, VillainsRule commented on client/multiplayer/room.js
> +        <span id="username-${userId}">${player.userId == 'QuizBotId' ? '<i class="fa-solid fa-robot"></i> ' : ''}${escapeHTML(username)}</span>
Can't userIDs be spoofed by a user if directly connecting to the WebSocket?

2024-05-16 20:25 UTC, VillainsRule commented on client/multiplayer/room.js
> +        upsertPlayerItem(quizBotPlayer);
Why doesn't the server send this player instead of the client?

2024-05-16 20:25 UTC, VillainsRule commented on server/TossupRoom.js
> +            this.settings.botDifficulty = message.value;
Please add invalidations for what this can be, from what I can tell a user could input a string as a value here.

2024-05-16 20:25 UTC, VillainsRule commented on server/TossupRoom.js
> +                    username: '🤖QuizBot🤖',
This username should be blacklisted from account creation or names in public games, as that could lead to impersonation/abuse.

2024-05-16 20:26 UTC, VillainsRule commented on client/multiplayer/room.js
> +        upsertPlayerItem(quizBotPlayer);
I might've misunderstood how these are added, if so, my bad.

2024-05-16 20:27 UTC, VillainsRule commented
\+ how hard would it be to add to singleplayer?

2024-10-01 01:26 UTC, UnderAK commented
Hey reviving this thread we should work on this soon.

2024-11-01 21:51 UTC, closed without merging